name: CI
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [ adopt@1.8, adopt@1.11 ]
    name: test on ${{ matrix.java }}
    steps:
      - uses: actions/checkout@v2
      - name: Cache jabba
        uses: pat-s/always-upload-cache@v1
        with:
          path: ~/.jabba
          key: jabba-${{ hashFiles('.github/workflows/*.yml') }}
      - name: Cache ivy
        uses: pat-s/always-upload-cache@v1
        with:
          path: ~/.ivy2/cache
          key: ivy-${{ hashFiles('**/build.sbt') }}-${{ hashFiles('project/*.scala') }}
      - name: Cache sbt
        uses: pat-s/always-upload-cache@v1
        with:
          path: ~/.sbt
          key: sbt-${{ hashFiles('**/build.sbt') }}-${{ hashFiles('project/*.scala') }}
      - name: Cache coursier
        uses: pat-s/always-upload-cache@v1
        with:
          path: ~/.coursier
          key: coursier-${{ hashFiles('**/build.sbt') }}-${{ hashFiles('project/*.scala') }}
      - uses: olafurpg/setup-scala@v7
        with:
          java-version: ${{ matrix.java }}
      - name: test
        run: sbt ++2.12.11 test scripted
