name: CI
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ adopt@1.8, adopt@1.11 ]
    name: test on ${{ matrix.java }}
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v7
        with:
          java-version: ${{ matrix.java }}
      - name: test
        run: sbt ++2.12.11 test scripted
