name: CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test:
    name: ${{ matrix.command }} / on ${{ matrix.java }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [ adopt@1.8, adopt@1.11 ]
        command:
          - "++2.12.11 test scripted"
          - "++2.10.7 test 'scripted sbt-scalafix/*'"
    steps:
      - uses: actions/checkout@v2
      - name: Cache ivy
        uses: actions/cache@v1
        with:
          path: ~/.ivy2/cache
          key: ivy-${{ runner.os }}-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('**/project/*.scala') }}
      - name: Cache sbt
        uses: actions/cache@v1
        with:
          path: ~/.sbt
          key: sbt-${{ runner.os }}-${{ hashFiles('**/build.sbt') }}-${{ hashFiles('**/project/*.scala') }}
      # https://get-coursier.io/docs/cache
      - name: Cache coursier
        uses: actions/cache@v1
        with:
          path: ~/.cache/coursier
          key: coursier-${{ runner.os }}-${{ hashFiles('**/build.sbt') }}-${{ hashFiles('**/project/*.scala') }}
      - uses: olafurpg/setup-scala@v7
        with:
          java-version: ${{ matrix.java }}
      - run: sbt ${{ matrix.command }}
  windows:
    name: Windows tests / on ${{ matrix.java }}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        java: [ adopt@1.8, adopt@1.11 ]
    steps:
      - uses: actions/checkout@v2
      - name: Cache ivy
        uses: actions/cache@v1
        with:
          path: ~/.ivy2/cache
          key: ivy-${{ runner.os }}-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('**/project/*.scala') }}
      - name: Cache sbt
        uses: actions/cache@v1
        with:
          path: ~/.sbt
          key: sbt-${{ runner.os }}-${{ hashFiles('**/build.sbt') }}-${{ hashFiles('**/project/*.scala') }}
      - name: Cache coursier
        uses: actions/cache@v1
        with:
          path: ~/AppData/Local/Coursier/Cache
          key: coursier-${{ runner.os }}-${{ hashFiles('**/build.sbt') }}-${{ hashFiles('**/project/*.scala') }}
      - uses: olafurpg/setup-scala@v7
        with:
          java-version: ${{ matrix.java }}
      - run: sbt ci-windows
        shell: bash
  checks:
    name: Scalafmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v7
      - run: ./bin/scalafmt --test
